define([], function() {
  return {
    "userLang": "en-us",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AboutUsTitle": "THIS IS US",
    "SiteLinksTitle": "MORE SITE SEEING",
    "SupportLinksTitle": "REACH OUT?",
    "LinkAboutUs": "About us",
    "LinkTerms": "Terms and conditions of use",
    "LinkPrivacy": "Privacy policy",
    "LinkSupport": "Support",
    "URLAboutUs": "https://gcxgce.sharepoint.com/SitePages/About-us.aspx",
    "URLTerms": "https://gcxgce.sharepoint.com/SitePages/Terms-and-Conditions.aspx",
    "URLPrivacy": "https://gcxgce.sharepoint.com/SitePages/Terms-and-Conditions.aspx#privacy-statement",
    "URLSupport": "https://gcxgce.sharepoint.com/sites/Support",
    "URLIntranet": "https://intranet.canada.ca/index-eng.asp",
    "URLCampus": "https://www.csps-efpc.gc.ca/GCcampus/index-eng.aspx",
    "LabelCampus":"Learning platform",
    "URLPedia": "https://www.gcpedia.gc.ca/wiki/Main_Page",
    "URLGCXchangeDirectory": "https://gcxgce.sharepoint.com/SitePages/GCXchangeDirectory.aspx",
    "LinkGCXchangeDirectory":"GCXchange Directory",
    "GovImage":"Government of Canada",
    "CanadaImage":"Symbol of the Government of Canada",  
  }
});