define([], function() {
  return {
    "userLang": "fr-fr",
    "PropertyPaneDescription": "Description",
    "BasicGroupName": "Group Name",
    "DescriptionFieldLabel": "Description Field",
    "AboutUsTitle": "NOTRE ÉQUIPE",
    "SiteLinksTitle": "VOIR LE RESTE DU SITE",
    "SupportLinksTitle": "COMMUNIQUEZ AVEC VOS COLLÈGUES",
    "LinkAboutUs": "À propos de nous",
    "LinkTerms": "Les conditions d' utilisation de GCÉchange",
    "LinkPrivacy": "Politique de confidentialité",
    "LinkSupport": "Soutien",
    "URLAboutUs": "https://gcxgce.sharepoint.com/SitePages/fr/About-us.aspx",
    "URLTerms": "https://gcxgce.sharepoint.com/SitePages/fr/Terms-and-Conditions.aspx",
    "URLPrivacy": "https://gcxgce.sharepoint.com/SitePages/fr/Terms-and-Conditions.aspx#%C3%A9nonc%C3%A9-de-confidentialit%C3%A9",
    "URLSupport": "https://gcxgce.sharepoint.com/sites/Support/SitePages/fr/Home.aspx",
    "URLIntranet": "https://intranet.canada.ca/index-fra.asp",
    "URLCampus": "https://www.csps-efpc.gc.ca/gccampus/index-fra.aspx",
    "LabelCampus":"Plateforme d'apprentissage",
    "URLPedia": "https://www.gcpedia.gc.ca/wiki/Main_Page?setlang=fr&uselang=fr",
    "URLGCXchangeDirectory": "https://gcxgce.sharepoint.com/SitePages/fr/GCXchangeDirectory.aspx",
    "LinkGCXchangeDirectory":"Annuaire GCÉchange",
    "GovImage":"Gouvernement du Canada",
    "CanadaImage":"Symbole du gouvernement du Canada",
    "ProtectedTermsURL": "https://gcxgce.sharepoint.com/SitePages/fr/Terms-and-Conditions-pro-b.aspx",
    "ProtectedTerms": "Les conditions d'utilisation de Pro A/B",
  }
});
